version: '3.4'

services:
  service-one:
    build: .
    container_name: service-one
    command: ./runserver.sh
    volumes:
      - .:/service-one
    ports:
      - "8101:8101"
    network_mode: "host"
    #restart: unless-stopped